### ISSUE TITLE
Is the process of from rgbd ros topic to lcm loss message?

### ISSUE THREAD

**Issue by tiexuedanxin** [MobileManipulation/rgbd_ros_to_lcm#10]
sorry to bother you, I use your rgbd_ros_to_lcm package and Labelfusion to create 6d pose datasets, the collect lcm message process is first "roslaunch openni2_launch openni2.launch" second "rviz" third "rgbd_ros_to_lcm" and finally lcm-logger, but when I use the collected lcm message to 3d reconstruction the result is poor compare the collect lcm message process "./openni2-camera-lcm" and "lcm-logger".could you give me some advice on how to solve the problem, thanks for advance.

**Comment by 5yler** [comment]
If you can use `openni2-camera-lcm` directly why are you using `rgbd_ros_to_lcm`? The purpose of `rgbd_ros_to_lcm` is to convert ROS messages into LCM format in cases where an LCM camera driver is not available.

My best guess is that your computing platform is not powerful enough to perform the conversion at the full frame rate, which results in partial data loss.

**Comment by tiexuedanxin** [comment]
> If you can use openni2-camera-lcm directly why are you using rgbd_ros_to_lcm? The purpose of rgbd_ros_to_lcm is to convert ROS messages into LCM format in cases where an LCM camera driver is not available.
> My best guess is that your computing platform is not powerful enough to perform the conversion at the full frame rate, which results in partial data loss.

The reason why I don't use the process of "./openni2-camera-lcm" and "lcm-logger" to collect data is when I collect data I can't see the camera image as same time, as I move the camera I can't guarant the target always in the camera field of view, so I use the first process to collect data publish it as ros topic visual image in rviz and convert it  LCM format to make lcm logger

**Comment by tiexuedanxin** [comment]
When I use you package to collect data, the post process of 3d Reconstruction performance is poor, I don't know why.Could you give me some advice on how to solve the problem, thanks for advance.

**Comment by 5yler** [comment]
If you open `lcm-spy` what is the frequency of messages on the `OPENNI_FRAME` channel?
