### ISSUE TITLE
Is it possible to use an existing sequence of RGB-D data?

### ISSUE THREAD

**Issue by danikhani** [MobileManipulation/rgbd_ros_to_lcm#12]
Hello is it possible to use already existed RGB-D images and convert them to lcm?

Thank you!

**Comment by 5yler** [comment]
Can you please describe your desired use case in more detail? The purpose of this package is to convert live ROS camera streams to LCM. It looks like you have a particular use in mind, but I am not sure if it is within scope for this project.

**Comment by danikhani** [comment]
Thank you very much. After your answer and a long research now I understand the purpose of your project.
