### ISSUE TITLE
Get errors when run catkin_make

### ISSUE THREAD

**Issue by hoangcuongbk80** [MobileManipulation/rgbd_ros_to_lcm#2]
Hi,
Thanks for your work! 
I am trying to build the code and getting the flowing issue:

![rgbtolcm](https://user-images.githubusercontent.com/10355081/42269446-74158f36-7f7e-11e8-9584-b7566f84f5bc.png)

Any suggestion would be appreciated!

My system: ubuntu 16.04, ROS kinetic.

**Comment by 5yler** [comment]
It looks like you are missing the VTK library. I would recommend you try `sudo apt-get install vtk6` and then run `catkin_make` again.

**Comment by hoangcuongbk80** [comment]
Thank you for your suggestion. It worked!
However when execute:
play a rosbag or run asus xtion camera
roslaunch rgbd_ros_to_lcm lcm_republisher.launch
run lcm-logger (Labelfusion to generate lcm file)
Finally, run run_trim in Labelfusion, however I cannot see anything:

![11](https://user-images.githubusercontent.com/10355081/42331212-28ecedfe-8075-11e8-8c95-6927d082077d.png)

Could you give me a suggestion? I am a bit urgent to collecting data, so if possible please help me ASAP. Thank you very much!!!!

**Comment by 5yler** [comment]
I'm not sure this pipeline will work to generate an lcmlog from playing back a rosbag, as the rate of messages published is likely lower than when streaming live images from the camera so the message synchronizer may fail.

A couple ideas:
- When you are running with the live camera, what is the output of lcm-logger? It should be listing the number of events saved each second
- Does the lcmlog that is generated have nonzero size? 
- What happens if you run lcm-spy? Does it show messages being published on the OPENNI_FRAME LCM channel?

**Comment by hoangcuongbk80** [comment]
Thanks for your prompt reply.

- Running with the live camera, the output of lcm-logger: original_log.lcmlog
-  Oh, the size of original_log.lcmlog file is 0 bytes
- run lcm-spy:

![13](https://user-images.githubusercontent.com/10355081/42334378-674c9fec-807d-11e8-8970-7988492e1e86.png)

**Comment by 5yler** [comment]
That's strange. I just cloned and installed the package on a new computer (Ubuntu 16.04, ROS Kinetic) and got the following output for lcm-logger:
![image](https://user-images.githubusercontent.com/10868851/42335716-3e95b300-804f-11e8-8953-ea7b4795f239.png)
lcm-spy: 
![image](https://user-images.githubusercontent.com/10868851/42335739-550349ae-804f-11e8-9d1d-88c920b732df.png)

Perhaps something is off with your LCM network setup. Is the computer you're running this on connected to the internet? If not, [this page](https://lcm-proj.github.io/multicast_setup.html) may be of help. Or is it perhaps connected to multiple network interfaces?

**Comment by hoangcuongbk80** [comment]
Oh, It worked if run  lcm-logger without starting the LabelFusion Docker container
So, the problem is from LabelFusion.

**Comment by 5yler** [comment]
Good to hear!
