### ISSUE TITLE
[LabelFusion] Cannot find above_table_pointcloud.vtp generated!

### ISSUE THREAD

**Issue by hoangcuongbk80** [MobileManipulation/rgbd_ros_to_lcm#3]
Sorry to bother you again and this issue is not associated with rgbd_ros_to_lcm, but I hope from your experience on LabelFusion might help. I am facing a new problem related to LabelFusion. 

I am learning to use the LabelFusion pipeline to generate datasets from lcmlog file in the smaller sample dataset downloaded from the website. From my understanding, a file like above_table_pointcloud.vtp should be generated after completing the step "segment the pointcloud above the table". However, flowing the instructions here: https://github.com/RobotLocomotion/LabelFusion/blob/master/README.rst, I couldn't see any file like that generated. I also described this issue on github:  https://github.com/RobotLocomotion/LabelFusion/issues/28; But no answer up to now!

If I create my own data, is it necessary to have above_table_pointcloud.vtp? I attempted to execute gr.launchObjectAlignment('drill') without above_table_pointcloud.vtp in the folder, then errors occured.

Could you give me some suggestions?

**Comment by 5yler** [comment]
I responded in the LabelFusion issue directly, closing this one as it's not related to this repository
