### ISSUE TITLE
How to use rgbd_ros_to_lcm in Labelfusion

### ISSUE THREAD

**Issue by CreateBetter** [MobileManipulation/rgbd_ros_to_lcm#5]
Hi! Thanks a lot for your rgbd_ros_to_lcm.But I am very sorry that we failed to use rgbd_ros_to_lcm in [labelfusion](https://github.com/RobotLocomotion/LabelFusion). Now, we can run your code in ros successfully ,but we can not find how the labelfusion subscribe the output

**Comment by 5yler** [comment]
Labelfusion operates on an lcmlog file with synchronized RGB and depth images. To generate such a logfile, launch the camera driver and `rgbd_ros_to_lcm` and then use `lcm-logger`. See the [LabelFusion readme](https://github.com/RobotLocomotion/LabelFusion#collect-raw-data-from-xtion) for more details on the pipeline one you have generated an lcmlog.

**Comment by CreateBetter** [comment]
Thank you very much~We have already solve this question, Thanks for your rgbd_ros_to_lcm.
