### ISSUE TITLE
Parameters setting

### ISSUE THREAD

**Issue by MengDes** [MobileManipulation/rgbd_ros_to_lcm#6]
my sensor is realsense D415 ，use together with Labelfusion https://github.com/RobotLocomotion/LabelFusion
i want to disable compress_rgb,compress_depth to get better quallity data.
here is my roslaunch file:  
      # input parameters
      subscribe_point_cloud: false
      #rgb_topic: /camera/rgb/image_rect_color
      rgb_topic: /camera/color/image_raw
      depth_topic: /camera/aligned_depth_to_color/image_raw

      #depth_topic: /camera/depth_registered/sw_registered/image_rect_raw
      cloud_topic: /camera/depth_registered/points

      # output parameters
      output_lcm_channel: "OPENNI_FRAME"
      compress_rgb: false
      compress_depth: false

      debug_print_statements: true

i recored success, but when i turn  to labelfusion docker , run_trim this lcmlog file 
error occur:
```
root@7735bcb889e1:~/labelfusion/data/log/test# run_trim
Found this many *lcmlogs:  1
Renaming to original_log.lcmlog
mv: 'original_log.lcmlog' and 'original_log.lcmlog' are the same file
Opening log player...
Opening viewer
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
LC: Disabling IPV6 support
LCM: Disabling IPV6 support
LCM: TTL set to zero, traffic will not leave localhost.
Exception: java.net.BindException: Address already in use (Bind failed)
Total seconds: 14.072087
==== LCM Warning ===
LCM detected that large packets are being received, but the kernel UDP
receive buffer is very small.  The possibility of dropping packets due to
insufficient buffer space is very high.

For more information, visit:
   http://lcm-proj.github.io/multicast_setup.html

Failed to get BotCamTrans for camera: OPENNI_FRAME_D
Failed to get coord_frame for camera: OPENNI_FRAME_D
unhandled image pixelformat 861030210 for camera OPENNI_FRAME_LEFT
WARNING: multisense_utils::unpack_multisense | image type not understood: 4
unhandled image pixelformat 861030210 for camera OPENNI_FRAME_LEFT
WARNING: multisense_utils::unpack_multisense | image type not understood: 4
unhandled image pixelformat 861030210 for camera OPENNI_FRAME_LEFT
WARNING: multisense_utils::unpack_multisense | image type not understood: 4
unhandled image pixelformat 861030210 for camera OPENNI_FRAME_LEFT
WARNING: multisense_utils::unpack_multisense | image type not understood: 4

```

i think this may not caused by rgbd_ros_to_lcm,but i was first time to know LCM,can you give me some tips ? thank you very much!

**Comment by 5yler** [comment]
Hi, I would recommend using the default settings and not disabling the compression. It's been a couple years since I have used LabelFusion but if I recall correctly there are some assumptions in the codebase about the format of the LCM log images (compressed being the standard). Let me know if that helps.

**Comment by MengDes** [comment]
thanks for you replay. very helpful

**Comment by 5yler** [comment]
You're welcome!
