### ISSUE TITLE
catkin_make fails, cannot find any vtk libraries

### ISSUE THREAD

**Issue by Pai-Sho** [MobileManipulation/rgbd_ros_to_lcm#7]
I have an issue similar to #2 where catkin_make fails with 

```
/usr/bin/ld: cannot find -lvtkCommon
/usr/bin/ld: cannot find -lvtkFiltering
/usr/bin/ld: cannot find -lvtkImaging
/usr/bin/ld: cannot find -lvtkGraphics
/usr/bin/ld: cannot find -lvtkGenericFiltering
/usr/bin/ld: cannot find -lvtkIO
/usr/bin/ld: cannot find -lvtkRendering
/usr/bin/ld: cannot find -lvtkVolumeRendering
/usr/bin/ld: cannot find -lvtkHybrid
/usr/bin/ld: cannot find -lvtkWidgets
/usr/bin/ld: cannot find -lvtkParallel
/usr/bin/ld: cannot find -lvtkInfovis
/usr/bin/ld: cannot find -lvtkGeovis
/usr/bin/ld: cannot find -lvtkViews
/usr/bin/ld: cannot find -lvtkCharts
collect2: error: ld returned 1 exit status
rgbd_ros_to_lcm/CMakeFiles/lcm_republisher.dir/build.make:678: recipe for target '/root/catkin_ws/devel/lib/rgbd_ros_to_lcm/lcm_republisher' failed
make[2]: *** [/root/catkin_ws/devel/lib/rgbd_ros_to_lcm/lcm_republisher] Error 1
CMakeFiles/Makefile2:571: recipe for target 'rgbd_ros_to_lcm/CMakeFiles/lcm_republisher.dir/all' failed
make[1]: *** [rgbd_ros_to_lcm/CMakeFiles/lcm_republisher.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed
```

I have ensured that `libvtk6-dev` and `lvtk6` are installed, and I have even tried compiling vtk from source to no avail. I am attempting to install this in the current LabelFusion docker image, is there a specific version of LCM and PCL that must be installed for everything to work correctly? Should I give up with the docker image and just try to install everything on my host machine?

**Comment by 5yler** [comment]
What is the output of `apt list --installed | grep vtk` in the docker?

Seems to be a linker error, I have never tried compiling the code in the LabelFusion docker - my recommendation would be to try and compile `rgbd_ros_to_lcm` outside the docker and use it to generate LCM logs, and then process those logs in the docker.

**Comment by Pai-Sho** [comment]
Yeah I'm thinking you're probably right. It would be nice to get everything working together in the docker if possible through. 

```
root@e4c59df64d21:~/catkin_ws# apt list --installed | grep vtk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvtk6-dev/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed]
libvtk6-java/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6-qt-dev/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6.2/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6.2-qt/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtkgdcm-cil/xenial,now 2.6.3-3ubuntu3 amd64 [installed]
libvtkgdcm-java/xenial,now 2.6.3-3ubuntu3 amd64 [installed]
libvtkgdcm-tools/xenial,now 2.6.3-3ubuntu3 amd64 [installed]
libvtkgdcm2-dev/xenial,now 2.6.3-3ubuntu3 amd64 [installed]
libvtkgdcm2.6/xenial,now 2.6.3-3ubuntu3 amd64 [installed]
python-vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
tcl-vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed]
```

**Comment by 5yler** [comment]
Odd. I have successfully installed outside a docker environment on an `i386` xenial machine and an `amd64` bionic machine, their output is as follows:
```
$ apt list --installed | grep vtk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

2004:libvtk6-dev/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
2005:libvtk6-java/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
2006:libvtk6-qt-dev/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
2007:libvtk6.2/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
2008:libvtk6.2-qt/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
2532:python-vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
2983:tcl-vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
3112:vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 i386 [installed,automatic]
```

```
$ apt list --installed | grep vtk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvtk6-dev/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
libvtk6-java/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
libvtk6-jni/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
libvtk6-qt-dev/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
libvtk6.3/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
libvtk6.3-qt/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
python-vtk6/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
tcl-vtk6/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
vtk6/bionic,now 6.3.0+dfsg1-11build1 amd64 [installed,automatic]
```
Let me know if building outside the docker works!

**Comment by Pai-Sho** [comment]
I was able to get everything running fine on the host machine, thank you!

**Comment by MrLuer** [comment]
> I was able to get everything running fine on the host machine, thank you!

I face the same problem，how did you solve it？

**Comment by 5yler** [comment]
@Pai-Sho Please list the output of `apt list --installed | grep vtk` and more details on your build environment (are you trying to do this in a docker, OS version, etc.)

**Comment by MrLuer** [comment]
root@a5064dbfa71d:~/catkin_ws# apt list --installed | grep vtk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvtk5.10/xenial,now 5.10.1+dfsg-2.1build1 amd64 [installed]
libvtk5.10-qt4/xenial,now 5.10.1+dfsg-2.1build1 amd64 [installed]
libvtk6-dev/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6-java/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6-qt-dev/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6.2/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
libvtk6.2-qt/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
lvtk-dev/xenial,now 1.2.0~dfsg0-1build1 amd64 [installed]
lvtk-doc/xenial,now 1.2.0~dfsg0-1build1 all [installed]
lvtk-tools/xenial,now 1.2.0~dfsg0-1build1 amd64 [installed]
python-vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
tcl-vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed,automatic]
vtk6/xenial,now 6.2.0+dfsg1-10build1+debian11.1+osrf1 amd64 [installed]

yes, I did it in the docker,and the host OS is ubuntu18.04,the docker OS is ubuntu16.04

**Comment by 5yler** [comment]
Please try the above suggestion: my recommendation would be to try and compile `rgbd_ros_to_lcm `outside the docker and use it to generate LCM logs, and then process those logs in the docker.

**Comment by MrLuer** [comment]
thank you for reply， I have solve it by another way

**Comment by TommasoBendinelli** [comment]
I also face the same problem

**Comment by 5yler** [comment]
@TommasoBendinelli Please list the output of apt list --installed | grep vtk and more details on your build environment (are you trying to do this in a docker, OS version, etc.)
Please also try the above suggestion: my recommendation would be to try and compile `rgbd_ros_to_lcm` outside the docker and use it to generate LCM logs, and then process those logs in the docker.

**Comment by TommasoBendinelli** [comment]
@5yler I fixed by following your suggestion.
